# Generated by Django 5.0.1 on 2024-03-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name_plural': 'Variacoes'},
        ),
    ]
