# Generated by Django 5.0.1 on 2024-03-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_curta',
            new_name='short_description',
        ),
    ]
