# Generated by Django 5.0.1 on 2024-03-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_rename_descricao_curta_produto_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='short_description',
            new_name='descricao_curta',
        ),
    ]
